### ISSUE TITLE
Whatsapp new message red icon

### ISSUE THREAD

**Issue by LiBOSS-CZ** [TheGoddessInari/rambox#103]
### Steps to reproduce

1. Get new unread message on Whatsapp

### Expected behavior

Red icon in tray and unread message counter in Tab

### Actual behavior

White icon in tray with no unread message counter

### ENVIRONMENT
> Rambox-OS: v0.5.18 
> OS: Windows 10 Pro
> Arch: x64
> BuildVersion: c34a98c

**Comment by TheGoddessInari** [comment]
Would you be able to see if 74fafc0 fixes it? I

Is there a developer API or some other way I can send messages to myself to ensure it's working any given day?

**Comment by LiBOSS-CZ** [comment]
If you make an artifact, I can test it. I dont know if some api exist, but if you 2 SIM you can send message from each other even with Whatsapp Bussiness account and normal Whatsapp or using dual apps.

**Comment by LiBOSS-CZ** [comment]
Seems to be OK. Great work

**Comment by LiBOSS-CZ** [comment]
Does not working again:-(

OS: Windows 10 Pro 1909 build 18363.752
Arch: x64
BuildVersion: 8871b6c

**Comment by LiBOSS-CZ** [comment]
Same problem again

OS: Windows 10 Pro 20H2 build 19042.630
Arch: x64
BuildVersion: b42bfb8

**Comment by TheGoddessInari** [comment]
This should be fixed with ce902fba.
