### ISSUE TITLE
Whatsapp does not start

### ISSUE THREAD

**Issue by chwba** [TheGoddessInari/rambox#105]
### Steps to reproduce

1.  Add WhatsApp service 
2.  Connect any phone by scanning Barcode

### Expected behavior

Whatsapp web finishes startup and is ready to use.

### Actual behavior

See  the message "Updating Whatsapp is out of date. Updating now.." forever.

### ENVIRONMENT
> Rambox-OS: v0.5.18
> OS: Windows 10 Pro 1809
> Arch: x64
> BuildVersion: [74fafc0 ](https://github.com/TheGoddessInari/rambox/commit/74fafc0a93b29680ea5650284bd5537ab6ec3124)(nightly) from [here](https://github.com/TheGoddessInari/rambox/releases/nightly/)
> Does this happen upstream: unknown

**Comment by TheGoddessInari** [comment]
It's sounding like related to #75. Have you tried the latest version, 74fafc0?

Unfortunately, I still don't see this, and it's still likely related to the Chrome Stable Channel update. Electron doesn't update that fast.

WhatsApp is really bad at this.

**Comment by chwba** [comment]
Seems to be related to #75 but not precisely. 1. He is using two Whatsapp accounts 2. His update seems to actually complete.

I think I just linked the wrong BuildVersion and am already using the very latest release. I always download the current nightly binarys from this link: https://github.com/TheGoddessInari/rambox/releases/download/nightly/Rambox-OS.Setup.0.5.18.exe
So I should be on [74fafc0 ](https://github.com/TheGoddessInari/rambox/commit/74fafc0a93b29680ea5650284bd5537ab6ec3124) already. Will change accordingly in first comment.

**Comment by chwba** [comment]
It seems to have fixed itself. It might have actually been related to my router. For a different reason I fully resetted and restarted it and afterwards it just worked again.
