### ISSUE TITLE
Dragging and drop for service tabs sometimes does not work

### ISSUE THREAD

**Issue by moghingold** [TheGoddessInari/rambox#14]
### Steps to reproduce

1. Have multiple services open in Rambox
2. Try to drag-and-drop on to a different position

### Expected behavior

Drag and drop of rambox tabs should work similarly to dragging and dropping browser tabs, where the tab stays under your mouse, visually hints at where its new position will be by pushing other tabs out of the way as it moves, and then updates its position when the mouse button is let go.

### Actual behavior

Sometimes, the desired behavior happens. Other times (and I have most consistently been able to reproduce this with TweetDeck and Skype), the following happens instead:

1. The tab will show its mouseover state, but will not follow the mouse or push other tabs out of the way if it is dragged to the left or right.
2. Trying to jockey the broken tab's position by moving other tabs around it will cause other tabs to "jump" into its place as soon as they are moved, making it difficult to tell whether or not the tab has landed in the desired position relative to other tabs.

### ENVIRONMENT

This happens on both Mac OS and Linux x64 (Arch) using rambox v0.5.18 built from master

**Comment by TheGoddessInari** [comment]
Try this again. This issue **should** be long defunct.

**Comment by TheGoddessInari** [comment]
I'll close this soon if I haven't heard anything to the contrary. Related race issues should've been cured a long time ago by various commits.
