### ISSUE TITLE
[Minor][Win] Start menu shortcut folder

### ISSUE THREAD

**Issue by RaydenX93** [TheGoddessInari/rambox#16]
Here's a very minor thing that I noticed.
The start menu shortcut for Rambox is currently created under "TheGoddessInari\Rambox.lnk". I believe it would be better to remove the subfolder and just put it under the start menu, so it's easier for the user to find.

Thanks

**Comment by TheGoddessInari** [comment]
I looked, and apparently the only way to remove this is to ditch the squirrel installer for one of the other options. This'd kill much hope of easy auto-update as well. I wouldn't mind, but someone may. Not that it works now anyway.

Squirrel forces the folder's creation regardless of what the user wants.

**Comment by TheGoddessInari** [comment]
I'll be pushing [testing](/TheGoddessInari/rambox/tree/testing) back to master once I get a few more usability issues fixed. NSIS is being used already there, and fixed notifications not to need Squirrel. Now even a 'bare' uninstalled copy of Rambox will get proper notifications and toasts on Windows.

**Comment by RaydenX93** [comment]
It works nicely now.
Thanks!
