### ISSUE TITLE
Rename the fork?

### ISSUE THREAD

**Issue by TheGoddessInari** [TheGoddessInari/rambox#28]
Downstream went [closed source with Pro](https://github.com/saenzramiro/rambox/issues/1810), would renaming the fork be appropriate?
I'm partial to perhaps Rambox-OS, where the OS is Open Source, Old School, whatever.
I don't think it's **required**, but would this be helpful to disambiguate?
It'd most-likely be a labeling change only, and not affect program or installer names.

**Comment by RaydenX93** [comment]
I'm no expert but i think it should be done to avoid future legal problems since upstream is turning into a commercial software.

**Comment by mgkprod** [comment]
What about LibreBox ?

**Comment by TheGoddessInari** [comment]
Is Rambox-open too on-the-nose?

**Comment by TheGoddessInari** [comment]
Decided on Rambox-OS because it's simple and to the point. Can always reopen if there's something better later, as it's mostly just cosmetic.

**Comment by white-gecko** [comment]
I think renaming it would be good to state that you are actually maintaining an independent fork and make your software discoverable. It took me quite some time to find out, that you are maintaining an active fork of rambox.

Naming suggestions:
Rambox -> **Ewebox** (male sheep=ram, female sheep=ewe)
Looking for ram (https://en.wikipedia.org/wiki/Ram), there is also the _ram cichlid_, so maybe call it **cichlid**. The _ram cichlid_ is actually a freshwater fish which would emphasize your move to fresh waters ;-)

**Comment by rodneyrod** [comment]
@white-gecko What about Ewechat (you-chat)?

**Comment by white-gecko** [comment]
Sounds good. I just think about how to move the focus from only chats to the other webservices, one can embed. Like todonotes and calendar. Maybe chat is to close in its meaning. Box is quite open but also has a closed character …
