### ISSUE TITLE
0.5.18: Issue: Whatsapp login after rambox restart

### ISSUE THREAD

**Issue by LiBOSS-CZ** [TheGoddessInari/rambox#31]
### Steps to reproduce

1.  Add Whatsapp account
2.  Shutdown rambox
3.  Start rambox

### Expected behavior

Login to Whatsapp and load main page

### Actual behavior

Rambox did not connect to Whatsapp. Removing the account and adding it again solve the issue but only until shutting down rambox.

### ENVIRONMENT

> Rambox-OS: v0.5.18 (latest to actual date)

> OS: Windows 10 Pro

> Arch: x64

**Comment by TheGoddessInari** [comment]
You mean it doesn't stay logged in? It's an issue with Electron and how it persists the storage sessions. Chrome can get around it, but not sure if Electron can. I'll look into it.

**Comment by LiBOSS-CZ** [comment]
No. I mean new connection. It simply does not connect again. You have to remove and add again Whatsapp account to connect.
It was working in original version 0.5.17 from @saenzramiro

**Comment by LiBOSS-CZ** [comment]
Helped me turn off passive listeners. But I have to remove whatsapp and readd again without using passive listeners.

![rambox_whatsapp_issue](https://user-images.githubusercontent.com/41294900/43758198-a8476100-9a1b-11e8-9b98-642d13effd32.png)

**Comment by TheGoddessInari** [comment]
Passive listeners shouldn't be causing that unless WhatsApp does something really weird (and it might), as it just defaults event listeners for mouse and touch events to passive. Stuff like mouse move, click, scrollwheel.
If you toggle developer tools and look at the console, does it give any errors?
I wasn't expecting problems with that quite so soon, as the changes are particularly benign.
Either way, I'm adding the mechanism to blacklist those features (by default) from the shipped service list.

**Comment by LiBOSS-CZ** [comment]
Yes. You are right. I have made further investigation and found that only granularity made this problem.

**Comment by TheGoddessInari** [comment]
Sounds like WhatsApp has some kind of race condition in their code. I'll try to reach out to them, but in the mean time will blacklist it for that feature.
The reason the timer granularity (and passive events) exist is that most things don't require really tight timing for setTimeout, and most things don't need active listening on mouse events.
Some apps (like Skype and ICQ) notoriously spinloop toward the CPU, repainting needlessly.
It's likely that passive mouse/touch events will the default on the web at some point, and setTimeout abuse on the web is well-documented.
That plus the Electron and a few other changes reduced CPU usage for me by over 80% compared to 0.5.17. For some services, it won't matter, but services should reasonably be prepared for both if they can run on arbitrary devices. The best solution is for them to not spinloop or do other horrible things on the web versions, but most services have  been unwilling to fix such issues.

If the web ever becomes a friendlier place, we can always default off.

Lowered granularity on setTimeout isn't against the standard, as the standard explicitly says you aren't guaranteed to get the timeout you specify, and most everything that needs a more consistent timing uses setInterval. I tested with all kinds of things, but didn't test loading on WhatsApp.

The latest Windows master artifacts are built at this time and will have the changes included. It's worth noting that [gitter.im](https://gitter.im/TheGoddessInari/rambox) will let people know when the build artifacts are updated for a particular commit. I'm sure there are more integrations I could add as well.

You can tell it's working if the checkbox for that option (like WhatsApp with timer granularity) doesn't show up.

**Comment by LiBOSS-CZ** [comment]
New version does not allow adding new services at all :-(

**Comment by LiBOSS-CZ** [comment]
Working

**Comment by RaydenX93** [comment]
I had the same problem but it disappeared after a while by itself

**Comment by TheGoddessInari** [comment]
It's probably not allowing service creation again. I hate ExtJS.
I'll see if it doesn't need to be disabled or hidden. It's just not wanting to let me get the service status if it's not being edited as an already-existing service.

**Comment by TheGoddessInari** [comment]
Looks like we'll just have to leave the two fields uneditable until the service is actually created for now.

If anyone knows a better way of handling this, let me know. I already tried countless different iterations, and making it a blacklist was the most sensible since if something is blacklisted for these particular features, it shouldn't negatively affect the service, while also preventing someone from actively shooting themselves in the foot if there's a serious issue (like with WhatsApp).

**Comment by TheGoddessInari** [comment]
This should be fixed for WhatsApp. If not, let me know. Other services will need to be added to a blacklist on an as-needed basis. Preferably any services so flagged can resolve things on their end.

The relatively minor usability issue is different and due to how ExtJS declares things, I'm not sure is able to be resolved until moving away from ExtJS.
