### ISSUE TITLE
WhatsApp is showing a update message and the only way to use it is pressing CTRL+R

### ISSUE THREAD

**Issue by rarriagada** [TheGoddessInari/rambox#348]
The screen show this message:

WHATSAPP WEB

WhatsApp works with Google Chrome 60+
To use WhatsApp, update Chrome or use Mozilla Firefox, Safari, Microsoft Edge or Opera.

UPDATE GOOGLE CHROME

	
	-
	> Hamsket 0.6.4
	> Electron 17.1.0
	> win32 x64 10.0.19044
	> 105cf23  (grafted, HEAD, tag: nightly, origin/105cf238fd66165d158fd0f4c3aee94af687a51e) Thu, 3 Mar 2022 03:38:34 -0800

**Comment by muhdiboy** [comment]
Already opened here: https://github.com/TheGoddessInari/hamsket/issues/346

**Comment by rarriagada** [comment]
Thanks, i'll close this report.
