### ISSUE TITLE
Rambox.appimage Icon from the taskbar is missing 

### ISSUE THREAD

**Issue by Lvaskz** [TheGoddessInari/rambox#38]
Ubuntu 18.04
Gnome 3.28.1
64 bits 
the icon from taskbar is missing 
see this 
https://github.com/ramboxapp/community-edition/issues/1541

**Comment by TheGoddessInari** [comment]
Was this tested vs this repo? We're already using a version of electron-builder that is supposed to fix this very issue.

As of electron-builder 20.26.0, it specifically addresses this.

**Comment by Lvaskz** [comment]
I am in ubuntu 18.04, 64 bits. As you can see, The issue remains

**Comment by TheGoddessInari** [comment]
Right. Well, like I said, it's an electron-builder upstream issue. I'll try to make a workaround.

See if https://ci.appveyor.com/api/projects/TheGoddessInari/rambox/artifacts/dist/Rambox-0.5.18-x86_64.AppImage?job=Image%3A%20Ubuntu&branch=testing works for you. If not, I'll try a different workaround.

**Comment by Lvaskz** [comment]
Nop, It is not working.

**Comment by TheGoddessInari** [comment]
Try the latest build at the same URL. If that doesn't fix it, unfortunately, it simply appears to be an upstream electron-builder bug. https://github.com/electron-userland/electron-builder/issues/2577

**Comment by Lvaskz** [comment]
Well, I tried, but same issue. Thats weird, I have cpod.appimage and unofficial protonmail desktop client , they are built in electron. The icons appear in the dock bar. I reported some issue with protonmail client about icon from app menu, is not fixed it yet, but in the dock looks right.

**Comment by TheGoddessInari** [comment]
I'll try and see what they use. electron-builder and electron-packager both look to have that bug. It works for some people, but I've tried every recommendation and troubleshooting hint. 

I don't have a separate linux machine I can test with right now.

**Comment by HanFox** [comment]
I was having this issue on Arch Linux using Plasma, but the latest commit (https://github.com/TheGoddessInari/rambox/commit/480dacaf5663ed64fe0a422c94e592ba2298b5bb) seems to have resolved it.

**Comment by TheGoddessInari** [comment]
Should've been fixed by 480daca or one of the other icon commits.
