### ISSUE TITLE
OSX build fails

### ISSUE THREAD

**Issue by TheGoddessInari** [TheGoddessInari/rambox#4]
It's a simple matter of that I'm using the "safe" shell variable expansion which for whatever reason is failing on OSX.

I need someone with OSX/MacOS to test this, as soon as that's fixed, MacOS builds will get put back.

**Comment by moghingold** [comment]
I have access to a Mac. I followed the compilation instructions in your README and was able to build for Mac OS without any problems whatsoever. Are there steps for reproducing this issue?

**Comment by TheGoddessInari** [comment]
Yes. It's the part from travis-ci to do the automated builds. Such as
```

**Comment by moghingold** [comment]
I just plopped those two commands into a terminal and ran them with no modifications -- `sencha.sh.zip` Downloaded with no issues.

Does travis-ci require using /bin/sh? Is the fact that I'm using a default terminal (i.e. /bin/bash) preventing me from reproducing this?

**Comment by TheGoddessInari** [comment]
I'm pushing on the testing branch to try to see if I can figure out what's wrong.
This is what happens: https://travis-ci.org/TheGoddessInari/rambox/jobs/405533910

I was looking into alternative CI hosts, but Mac builds would need to run on a Mac host besides.

Feel free to go the gitter.im link if you wanted to talk with greater frequency on this.

**Comment by TheGoddessInari** [comment]
MacOS builds have been working, move discussion to #12 as we focus on artifact hosting rather than the build system, which now works and passes.
