### ISSUE TITLE
Compilation Failure on Win64 possibly related to Sencha / Compass 

### ISSUE THREAD

**Issue by DrXadium** [TheGoddessInari/rambox#51]
### Steps to reproduce

1. Installed all prerequisite software (Sencha is installed WITH compass extension). Apps added to Environment Variable 
2. Attempted compilation as per guide. 
3. Ran both  npm run repack:win64 / npm run setup

### Expected behavior

Compilation should complete

### Actual behavior

Compilation fails with the following: 

Z:\temp\rambox2\rambox\.sencha\app\build-impl.xml:291: The following error occurred while executing this line:
Z:\temp\rambox2\rambox\.sencha\app\sass-impl.xml:205: The following error occurred while executing this line:
Z:\temp\rambox2\rambox\.sencha\app\sass-impl.xml:297: Problem: failed to create task or type x-compass-compile
Cause: The name is undefined.
Action: Check the spelling.
Action: Check that any custom tasks/types have been declared.
Action: Check that any <presetdef>/<macrodef> declarations have taken place.

### ENVIRONMENT

> Rambox-OS: v0.5.18

> OS: Windows 10

> Arch: x64  

> Does this happen upstream: unknown

This appears to be compass related. I have installed and verified the operation of compass. If I comment out the block of code starting on line 205 of \rambox\.sencha\app\sass-impl.xml I can compile, but styles are broken and the interface is basically unusable.  I am unsure if the stylesheets needed for the project are not included or if there is some other issue I can dig into. 

Should there be other files under https://github.com/TheGoddessInari/rambox/tree/master/sass ?

 

Sencha Cmd 6.5.3.6 - Crash report
================================================
An error occurred while executing the following command: app build

Diagnostic information:
=======================
                         app.archivePath : archive                                           
                      app.bootstrap.base : Z:\temp\rambox2\rambox                            
                       app.bootstrap.css : bootstrap.css                                     
                  app.bootstrap.manifest : bootstrap.json                                    
               app.bootstrap.microloader : bootstrap.js                                      
                        app.cache.deltas : deltas                                            
                           app.classpath : Z:\temp\rambox2\rambox/app                        
                         app.cmd.version : 6.6.0.13                                          
                          app.compressor : null                                              
                          app.config.dir : Z:\temp\rambox2\rambox\.sencha\app                
                   app.cordova.config.id : com.domain.Rambox                                 
                 app.cordova.config.name : Rambox                                            
                 app.cordova.config.path : Z:\temp\rambox2\rambox/cordova                    
               app.cordova.config.target :                                                   
              app.cordova.config.verbose : false                                             
                   app.cordova.js.0.path : cordova.js                                        
               app.cordova.js.0.priority : 1000                                              
                 app.cordova.js.0.remote : true                                              
                   app.cordova.js.length : 1                                                 
                 app.cordova.microloader : Z:\temp\rambox2\rambox\.sencha\app/Microloader.js 
                 app.cordova.output.base : Z:\temp\rambox2\rambox/cordova/www                
         app.cordova.output.cache.enable : false                                             
        app.cordova.output.deltas.enable : false                                             
     app.development.output.cache.enable : false                                             
    app.development.output.deltas.enable : false                                             
                                 app.dir : Z:\temp\rambox2\rambox                            
                           app.framework : ext                                               
                   app.framework.version : 5.1.1.451                                         
                                  app.id : 0f59c907-ae2e-485e-8a8d-cc2f7f60c1ed              
                       app.indexHtmlPath : index.html                                        
                                app.name : Rambox                                            
              app.output.appCache.enable : true                                              
                         app.output.base : Z:\temp\rambox2\rambox/build/${build.environment}/Rambox
                 app.output.cache.enable : false                                             
                app.output.deltas.enable : false                                             
                   app.output.js.version : ES6                                               
           app.output.microloader.enable : true                                              
                           app.overrides : Z:\temp\rambox2\rambox/overrides                  
                           app.page.name : index.html                                        
                  app.phonegap.config.id : com.domain.Rambox                                 
                app.phonegap.config.name : Rambox                                            
                app.phonegap.config.path : Z:\temp\rambox2\rambox/phonegap                   
              app.phonegap.config.remote : false                                             
             app.phonegap.config.verbose : false                                             
                  app.phonegap.js.0.path : phonegap.js                                       
              app.phonegap.js.0.priority : 1000                                              
                app.phonegap.js.0.remote : true                                              
                  app.phonegap.js.length : 1                                                 
                app.phonegap.microloader : Z:\temp\rambox2\rambox\.sencha\app/Microloader.js 
                app.phonegap.output.base : Z:\temp\rambox2\rambox/phonegap/www               
        app.phonegap.output.cache.enable : false                                             
       app.phonegap.output.deltas.enable : false                                             
     app.production.compressor.polyfills : none                                              
          app.production.compressor.type : cmd                                               
                      app.resource.paths : Z:\temp\rambox2\rambox/resources                  
                        app.sass.etcpath : Z:\temp\rambox2\rambox/sass/etc/all.scss          
                      app.sass.namespace : Rambox                                            
                        app.sass.srcpath : Z:\temp\rambox2\rambox/sass/src                   
                        app.sass.varpath : Z:\temp\rambox2\rambox/sass/var                   
        app.slicer.js.0.isWidgetManifest : true                                              
                    app.slicer.js.0.path : Z:\temp\rambox2\rambox/sass/example/custom.js     
                    app.slicer.js.length : 1                                                 
          app.slicer.output.cache.enable : false                                             
         app.slicer.output.deltas.enable : false                                             
         app.testing.output.cache.enable : false                                             
        app.testing.output.deltas.enable : false                                             
                               app.theme : rambox-default-theme                              
                    buildenvironment.dir : Z:\temp\rambox2\rambox                            
               buildenvironment.load.dir : Z:\temp\rambox2\rambox                            
                          cmd.config.dir : C:\Users\[REDACTED]\bin\Sencha\Cmd\6.5.3.6        
                                 cmd.dir : C:\Users\[REDACTED]\bin\Sencha\Cmd\6.5.3.6        
                    cmd.framework.minver : 5.0.0                                             
                   cmd.framework.version : 5.4.99.9999                                       
              cmd.merge.tool.args.araxis : -wait -merge -3 -a1 {base} {user} {generated} {out}
              cmd.merge.tool.args.kdiff3 : {base} {user} {generated} -o {out}                
             cmd.merge.tool.args.p4merge : {base} {user} {generated} {out}                   
           cmd.merge.tool.args.smartsync : {user} {generated} {base}                         
          cmd.merge.tool.args.sourcegear : --merge --result={out} {user} {base} {generated}  
            cmd.merge.tool.args.tortoise : -base:{base} -theirs:{generated} -mine:{user} -merged:{out}
                              cmd.minver : 3.0.0.0                                           
                            cmd.platform : windows                                           
                     cmd.unicode.escapes : C:\Users\[REDACTED]\bin\Sencha\Cmd\6.5.3.6/unicode-escapes.json
                             cmd.version : 6.5.3.6                                           
                            cmd.web.port : 1841                                              
                     config.skipDownload : true                                              
                      config.skipInherit : false                                             
                                 ext.dir : Z:\temp\rambox2\rambox/ext                        
                        ext.license.name : gpl                                               
                     framework.classpath : Z:\temp\rambox2\rambox\ext/src                    
                    framework.cmd.minver : 5.1.3.61                                          
                   framework.cmd.version : 5.1.3.61                                          
                 framework.compatVersion : 4.0                                               
                    framework.config.dir : C:\Users\[REDACTED]\bin\Sencha\Cmd\6.5.3.6\plugins\ext\5.1
                       framework.creator : Sencha                                            
           framework.detailedDescription : Sencha Ext JS JavaScript Framework                
                           framework.dir : Z:\temp\rambox2\rambox\ext                        
                        framework.format : 1                                                 
                          framework.isV5 : true                                              
                         framework.local : true                                              
                          framework.name : ext                                               
                        framework.output : ${package.dir}/build                              
                  framework.packages.dir : Z:\temp\rambox2\rambox\ext/packages               
                       framework.summary : Ext JS                                            
                          framework.type : framework                                         
                       framework.version : 5.1.1.451                                         
                       inspector.address : http://localhost:1839/                            
                          repo.local.dir : C:\Users\[REDACTED]\bin\Sencha\Cmd\repo           
                       shared.sencha.dir : false                                             
        system.java.net.useSystemProxies : true                                              
                              theme.name : rambox-default-theme                              
                     workspace.build.dir : Z:\temp\rambox2\rambox/build                      
                   workspace.cmd.version : 6.0.2.14                                          
                    workspace.config.dir : Z:\temp\rambox2\rambox\.sencha\workspace          
                           workspace.dir : Z:\temp\rambox2\rambox                            
           workspace.frameworks.ext.path : Z:\temp\rambox2\rambox\ext                        
        workspace.frameworks.ext.version : 5.1.1.451                                         
                  workspace.packages.dir : Z:\temp\rambox2\rambox/packages/local,Z:\temp\rambox2\rambox/packages
              workspace.packages.extract : Z:\temp\rambox2\rambox/packages/remote            
                     workspace.theme.dir : Z:\temp\rambox2\rambox/packages/local,Z:\temp\rambox2\rambox/packages/${args.themeName}

**Comment by DrXadium** [comment]
Closing this as I resolved it by deleting everything and starting over with a fresh pull in c:\temp. I suspect nesting the folders caused issues. But one thing I did try prior which may have helped also was installing an older version of Sencha and then updating it from the command line with the command _sencha upgrade_

**Comment by TheGoddessInari** [comment]
I see you closed this after fixing it. I'm not sure if that particular 'sass' folder is required by Sencha or not, but no, it's not supposed to have anything useful in there.
