### ISSUE TITLE
Feature request: CSS injection

### ISSUE THREAD

**Issue by moghingold** [TheGoddessInari/rambox#6]
"Upstream" already has an issue for this that has languished: https://github.com/saenzramiro/rambox/issues/44

The use case for this would be to force services that do not natively support dark themes (eg Slack) to use colors that are less harsh on bright monitors. This is a low priority as there already exists a workaround via the "Custom Code" feature, in which an `applycss()` function can be trivially created, or in which full styles from userstyles.org can be pasted as javascript.

However, this would definitely be a nice-to-have, as native CSS injection would have less performance overhead than CSS-by-way-of-JS.

**Comment by TheGoddessInari** [comment]
Latest commit supports custom CSS injection, tested and working.

**Comment by TheGoddessInari** [comment]
It's worth noting that, unlike Stylish/Stylus, it doesn't appear to be affecting things like iframes, but neither does the "standard" CSS injector you'd use in the javascript custom box.
