### ISSUE TITLE
Meaningless warnings about insecure connections to file:// URIs

### ISSUE THREAD

**Issue by nvesely** [TheGoddessInari/rambox#60]
### Steps to reproduce

1. Use any HTTPS web app in Rambox.

### Expected behavior

No warnings about "insecure" connections to my local filesystem.

### Actual behavior

A blue warning banner is popping up sometimes (not sure why not always) on the bottom of the screen due to the fact the main origin, `file://`, is "not secure." Even though the warning banner doesn't always come up, if you look under the Security tab of the developer tools you can still always see this.

### ENVIRONMENT

Version: 0.5.18
Platform: linux (x64)
Electron: 2.0.11
Chromium: 61.0.3163.100
Node: 8.9.3

> Does this happen upstream:

no

**Comment by TheGoddessInari** [comment]
Does it say what URLs are being warned about? And was it compiled or using a package?

**Comment by nvesely** [comment]
Latest package. I think it's because it's interpreting file:// as an origin that should be considered in the mixed-content policy. So the connections to the origin and 3rd parties will be secure, but then this false error show up.

**Comment by TheGoddessInari** [comment]
Let me guess, is this with a Master Password?

**Comment by nvesely** [comment]
No, but also I don't know what a "Master Password" is.

**Comment by TheGoddessInari** [comment]
Under preferences you can make it ask for a master password at startup. It's the only other thing that uses file:// in the codebase.

Are you sure there's not a virus, network proxy, etc interfering with requests? Nothing should be using file://.

Take screenshots, as well, if you please. I've never seen the blue bar or insecure origin prompt you're talking about.

**Comment by nvesely** [comment]
I haven't been able to reproduce the warning bar, but if you go into Developer Tools > Security you see this

![screenshot from 2018-12-08 17-43-21](https://user-images.githubusercontent.com/3538418/49688893-d7995980-fb10-11e8-8815-06f8fca6a466.png)

Now, this warning is really a false positive and because it's out of the way of users nothing to worry about. OTOH, the banner that popped up was an actual problem because it may unnecessarily worry users.

> Under preferences you can make it ask for a master password at startup. It's the only other thing that uses file:// in the codebase.

Nothing in the webviews should be accessing `file://`, but it looks like the resources that compose the Rambox app GUI are loaded from the local filesystem as one might expect:

![screenshot from 2018-12-08 17-46-13](https://user-images.githubusercontent.com/3538418/49688921-41b1fe80-fb11-11e8-87a1-a7204ba57582.png)

**Comment by TheGoddessInari** [comment]
Perhaps this is because of whatever the AppImage is doing, I'll check it when I'm over in Linux.

**Comment by TheGoddessInari** [comment]
I forgot to ask, has this been tried with current `master`? Icons are now relative.
