### ISSUE TITLE
Startup race

### ISSUE THREAD

**Issue by TheGoddessInari** [TheGoddessInari/rambox#61]
I noticed this with upstream, too, but maybe someone can help narrow this down.

The software often (when disk activity is present) 'races' and presents a 'dead' session that can't load anything and has to be killed. The second session always works.

**Comment by TheGoddessInari** [comment]
Funny enough, it looks like this is more-or-less solved by Electron 3.0.x, but have to solve the shortcut issue.

**Comment by vraravam** [comment]
I am still running the latest released version of Rambox which uses Electron 2.0.8, and am also seeing the same issue (race condition as soon as startup).

**Comment by TheGoddessInari** [comment]
Fixed by 86c72dda6cdc900f6ee2897642b32cbd7bdff4f5.
