### ISSUE TITLE
Remove old URL from GitHub project description.

### ISSUE THREAD

**Issue by ontherunvaro** [TheGoddessInari/rambox#62]
As I mentioned in #32, the link "website" URL in the github page for this repo still points to http://rambox.pro.

This is a bit confusing for new users: I just recommended this fork to a friend and he went to download the software from that URL, which of course ended in him downloading the old unmantained source fork.

Please remove the URL! And thanks for all your work

**Comment by TheGoddessInari** [comment]
Done.
