### ISSUE TITLE
All non-menu shortcuts stop working with Electron 3.0.x.

### ISSUE THREAD

**Issue by TheGoddessInari** [TheGoddessInari/rambox#66]
It looks like Electron 3.0.x changes the scoping rules out from under the ExtJS Ext.util.keymap referenced in app/Application.js. So they only apply to the "home" window.

Given that this change appears undocumented, I'm taking the time to isolate the problem, but could probably use help with a workaround.

**Comment by TheGoddessInari** [comment]
Looks like this is broken by https://github.com/electron/electron/commit/44b0245ac4336fa3cd94b5184f9a2dbf1226b66f, which funny enough isn't documented in the release notes for 3.0.0, let alone that it's a breaking API change. Fun.

**Comment by TheGoddessInari** [comment]
There's this sort of thing, but the ExtJS KeyMap appears a bit convoluted with how it sets up and then processes events. https://github.com/electron/electron/issues/14258#issuecomment-416893856

The best solution would probably be to process `before-input-event` and pass the appropriately modified event along. We can override ExtJS KeyMap functions, I'm just not sure how to bridge the keyboard wrapper to the rest of KeyMap, as it's not working as expected. I'll think about it more later.

One of the reasons I want to get away from all of the ExtJS, among other things, is that it's seriously impossible to debug code that's not at the user-input level, nor websites (for the most part).

**Comment by TheGoddessInari** [comment]
This is still expected to be broken at the present time. I'm still investigating workarounds. If there's anything you could bring to my attention, it'd be greatly appreciated.

**Comment by TheGoddessInari** [comment]
I've come up with a fix. It'll be uploaded later today if everything goes well.

**Comment by ThauEx** [comment]
Some of the key shortcuts are not working fine for me on macOS...
For example zoom works only for the first active tab, in my case the last one. I can press cms++ or cmd+- in any tab, but the zoom happens only in this one tab.
cmd+-> or cmd+<- works only, when I click the tab bar and I have to click again into it, to switch to the next tab, because after the tab change, the tab content is interpreting the cmd+->/cmd+<- commands.

**Comment by TheGoddessInari** [comment]
I'll have to investigate zoom, as it's probably a weird electron issue. It works the same way as before.
From the code, I preserved everything except ctrl+1 through ctrl+9. I could but it'd be more than a little wasteful.

What keybind are you describing? It seems like you're saying cmd+shift+<? But that doesn't seem right, as it wasn't bound in the code before. Ctrl+, goes to the home tab. Cmd+tab and cmd+pagedown, and their respective backwards moving ones, were the two in the code for going to next tab.

I changed where stuff was bound, but not what was bound, unless I'm missing something really obvious.

**Comment by ThauEx** [comment]
Sorry for the missunderstanding:   
cmd+-> = ⌘ + →
cmd+<- = ⌘ + ←

⌘ + [TAB] I have to test again, but I think I had issues with it too, because the tab content is interpreting this command and not the rambox window itself.

**Comment by TheGoddessInari** [comment]
Sorry for the delay. Killer week. Just so I'm clear, there is or were shortcuts for ⌘ + → and ⌘ + ←, not in this code?, that worked on electron 2.0 and Rambox CE?

Don't suppose you'd happen to know if there was a windows equivalent in control + → and control + ←?

**Comment by ThauEx** [comment]
There are, those are the shortcuts for next tab and previous tab. When using [Display?] -> [Commands] -> [Next Tab], it works fine, but not with the suggested shortcuts. I don't know, I cannot remember, if this was working on electron 2.0, I only remember [CTRL]+[TAB] and ⌘ + [number] was working.

⌘ + → should be the windows equivalent for [CTRL]+ →. The shortcut ⌘ + → is "working", but only if I activate the current service tab first, e.g. click current tab, press ⌘ + → (changes to the next tab), click current active tab, press ⌘ + →. If I don't click the active tab, it sends the command to the tab content and not to rambox, thus something happens inside the tab.

**Comment by TheGoddessInari** [comment]
I made a build with those specific shortcuts added, and it does the behavior you're specifying. Only works on home tab unless you're already clicked onto the tabs themselves.

Alt + → and Alt +  ← work as expected, so it's probably another Electron quirk.

**Comment by TheGoddessInari** [comment]
Unfortunately, I **am** seeing a different bug. Using the menu shortcuts, it's taking input focus away from the web controls, unlike with clicking.
