### ISSUE TITLE
Skype settings retain

### ISSUE THREAD

**Issue by LiBOSS-CZ** [TheGoddessInari/rambox#68]
### Steps to reproduce

1. Sign in to Skype
2. Set in settings to not show large emoticons
3. Reload skype with CTRL+R or restart Rambox

### Expected behavior

Setting persists

### Actual behavior

The switch setting actually persist but you see large emoticons in the chat and you have to turn this setting on and off again.

### ENVIRONMENT

> Rambox-OS: v0.5.18.174

> OS: Windows 10 Pro

> Arch: x64

**Comment by TheGoddessInari** [comment]
I haven't been able to replicate this on Skype or Skype Preview since it was reported.

**Comment by LiBOSS-CZ** [comment]
I have done some research and it has to be last message in chat and only smiley, but problem is server/skype side. I have tried same thing in Firefox with same bad results.
