### ISSUE TITLE
Confused about 'official' release

### ISSUE THREAD

**Issue by chwba** [TheGoddessInari/rambox#69]
I was just about to make a chocolatey package for this release but then I got a little confused because there was already a chocolatey package named as rambox-community-edition.

![screenshot_3](https://user-images.githubusercontent.com/22568014/48898204-79038880-ee4c-11e8-9f7b-e9496fd205f5.png)

So this is dead or not.? https://github.com/ramboxapp/community-edition It seems to be version 0.62 which is more current than this ones 0.58.

Im just confused because it still works, so why do we have this version as well exactly?

**Comment by TheGoddessInari** [comment]
This isn't dead, I'm just the only one working on it at the moment, and I'm not interested in following someone else's arbitrary release scheme.

I'm taking quality seriously and haven't wanted to release with a huge number of bugs. Check closed and locked issues for upstream's policy on that .

I'm happy to accept contributions, I'll be working on a few things by the weekend.

Upstream still has serious issues and still hasn't shown interest in much beyond paying lip service to open source and promoting their commercial version which costs a monthly fee.

This version is vastly more stable in most areas as well, but I'm still working on that and any help is appreciated. The upstream code base was and still is a mess.

Have a good day, it's Thanksgiving holiday where I live, and I am on mobile for today.

**Comment by DrXadium** [comment]
Thanks for your hard work. It IS appreciated, believe me.

**Comment by vraravam** [comment]
I think there was an issue (#28 ) about renaming this fork - if that is done quickly, this confusion could be avoided. Could the repo and all other places reflect that name change?

**Comment by TheGoddessInari** [comment]
As mentioned in #32, the problem is that changing the name changes the data saving/location/etc. There needs to be an intermediate release that can hopefully load old rambox data and export it, so that you'd be able to reimport it.

There's only one 'big' release blocker in #66, but I can release without that fixed anyway if people want.
It's an annoyance, but not critical to functionality.

**Comment by TheGoddessInari** [comment]
Since a release will be soon, for some definitions of soon, this'll effectively be fixed when #32 is, and #32 is no longer hard blocking on bugs or usability issues I believe.

File issues if there's something I don't know about! :)
