### ISSUE TITLE
Feature request: monospaced font in "Custom Code" field

### ISSUE THREAD

**Issue by moghingold** [TheGoddessInari/rambox#7]
Low priority, as this does not stop the "Custom Code" field from working. This (and, dare I dream, line numbers?) would make it much easier to work with code that has already been pasted in, however. If https://github.com/TheGoddessInari/rambox/issues/6 is implemented, this feature would be a good fit for that, as well.

**Comment by TheGoddessInari** [comment]
Rebuild from master, this should fix it. :)

**Comment by moghingold** [comment]
Built from master, not working on Arch Linux x64. Will test on Mac OS on Monday.

**Comment by TheGoddessInari** [comment]
I might've misread something. I'll look into it today.
