### ISSUE TITLE
[Contributor] Unable to follow instructions

### ISSUE THREAD

**Issue by vraravam** [TheGoddessInari/rambox#71]
### Steps to reproduce

1. Clone the git repo
2. Follow the instructions to build/run the app locally

### Expected behavior

I expected to be able to run the app *without any modifications* once I downloaded the git repo.

### Actual behavior

I installed the following versions of the system-prerequisites:
1.  
```
node -v
v10.11.0

Sencha Cmd: v6.5.3.6

git rev-parse HEAD
1dd0cbb2eab308bdda318e1b0ab3d945209849c0
```

I get the following error:
```
Sencha Cmd v6.5.3.6
[INF] Using GPL version of Ext JS version 5.1.1.451 from ~/tmp/rambox/ext.
[INF] The implications of using GPL version can be found here (http://www.sencha.com/products/extjs/licensing).
[INF] Processing Build Descriptor : default (development environment)
[INF] Starting server on port : 1841
[INF] Mapping http://localhost:1841/~cmd to ~/bin/Sencha/Cmd/6.5.3.6...
[INF] Mapping http://localhost:1841/ to ~/tmp/rambox...
[INF] Server started at port : 1841
[INF] Application available at http://localhost:1841
[INF] Loading compiler context
[INF] Loading app json manifest...
[INF] Appending content to ~/tmp/rambox/bootstrap.js
[INF] Writing content to ~/tmp/rambox/bootstrap.json
[INF] merging 424 input resources into ~/tmp/rambox/build/development/Rambox/resources
[INF] merged 424 resources into ~/tmp/rambox/build/development/Rambox/resources
[INF] merging 123 input resources into ~/tmp/rambox/build/development/Rambox
[INF] merged 123 resources into ~/tmp/rambox/build/development/Rambox
[INF] Writing content to ~/tmp/rambox/build/temp/development/Rambox/slicer-temp/bootstrap.json
[INF] Writing content to ~/tmp/rambox/build/temp/development/Rambox/slicer-temp/bootstrap.js
[INF] writing sass content to ~/tmp/rambox/build/temp/development/Rambox/sass/Rambox-all.scss.tmp
[INF] appending sass content to ~/tmp/rambox/build/temp/development/Rambox/sass/Rambox-all.scss.tmp
[INF] appending sass content to ~/tmp/rambox/build/temp/development/Rambox/sass/Rambox-all.scss.tmp
[INF] writing sass content to ~/tmp/rambox/build/temp/development/Rambox/sass/config.rb

[ERR] ~/bin/Sencha/Cmd/6.5.3.6/plugin.xml:378: The following error occurred while executing this line:
~/tmp/rambox/.sencha/app/build-impl.xml:252: The following error occurred while executing this line:
~/tmp/rambox/.sencha/app/watch-impl.xml:87: The following error occurred while executing this line:
~/tmp/rambox/.sencha/app/build-impl.xml:291: The following error occurred while executing this line:
~/tmp/rambox/.sencha/app/sass-impl.xml:205: The following error occurred while executing this line:
~/tmp/rambox/.sencha/app/sass-impl.xml:297: Problem: failed to create task or type x-compass-compile
Cause: The name is undefined.
Action: Check the spelling.
Action: Check that any custom tasks/types have been declared.
Action: Check that any <presetdef>/<macrodef> declarations have taken place.

[ERR] A log is available in the file "~/tmp/rambox/sencha-error-20181126.log"
[ERR]
[ERR] The application was last modified by an older version of Sencha Cmd (6.6.0.13).
[ERR] Installing a newer Sencha Cmd version may resolve the error described above.
[ERR]
```
### ENVIRONMENT

> Rambox-OS: v0.X.X

> OS: XXXX

> Arch: x64 or ia32

> Does this happen upstream: yes, no, unknown, or N/A

**Comment by TheGoddessInari** [comment]
Try this with Sencha Cmd 6.6.0.13, as it says. With ruby installed it 'works for me', but the 'app watch' stuff has never really worked, as upstream never really implemented anything with regard to it, just like unit tests.

**Comment by vraravam** [comment]
@TheGoddessInari - looks like there might be something missing then. I was following the exact steps in the README to get the app "up and running". If you are saying that `sencha app watch` never worked, then what commands do I need to run and how do I get to the UI? I am sorry, I'm not a javascript dev - so, i wanted to run the latest and greatest and provide beta-testing as my contribution.

**Comment by BrechtSerckx** [comment]
The steps in Compile should work.
```
git clone https://github.com/TheGoddessInari/rambox.git
cd rambox
npm install
npm run repack:YOUR_PLATFORM
```
The Contributing section is, if I understand correctly, for if you want to contribute to development directly,.

**Comment by vraravam** [comment]
@BrechtSerckx - yes, exactly. In case it wasn't clear, I would like to run the app locally from the master branch of the codebase. Since there's no build for mac OS, running the app using the code is the only way I could think of. Do you have any other ideas/suggestions?

**Comment by vraravam** [comment]
ok - looks like there are conflicting steps: in the whole codebase, if you search for `npm install` - there are 3 hits - each stating different steps.

**Comment by BrechtSerckx** [comment]
> @BrechtSerckx - yes, exactly. In case it wasn't clear, I would like to run the app locally from the master branch of the codebase. Since there's no build for mac OS, running the app using the code is the only way I could think of. Do you have any other ideas/suggestions?

That what it is doing, it locally builds the app for you from the master branch. You have to run `npm run repack:osx` to build it for macOS, npm/electron-builder will take care of the rest. You can see what it is doing in package.json.

**Comment by TheGoddessInari** [comment]
Oh, I can see how the README could be a little misleading. If you follow the steps under Compiling particularly `npm run setup` instead of `npm run repack`, it'll produce installer binaries in the `dist` directory. `npm run repack` will produce a directory of plain binaries that you can run, or copy over an existing installation.

**Comment by vraravam** [comment]
I ran `npm run repack` as per the above comment, but I still get the error as seen in the attached screenshot. I'm not sure if its an issue with my versions of node, etc. I have also attached the log file that was created.

Screen capture of command-line output:
<img width="1151" alt="screenshot 2018-12-02 at 8 34 40 am" src="https://user-images.githubusercontent.com/69629/49335133-540dd300-f60d-11e8-84f0-2ee7d850d9ec.png">

Log file: [2018-12-02T03_01_54_879Z-debug.log](https://github.com/TheGoddessInari/rambox/files/2636557/2018-12-02T03_01_54_879Z-debug.log)

**Comment by TheGoddessInari** [comment]
I'll clarify instructions; as with previous comment though, it's likely the actual error here is that Compass and/or Ruby wasn't installed.

**Comment by TheGoddessInari** [comment]
Clarified instructions with 38bffd64678057a27c53d0160ac75632219466bf.
