### ISSUE TITLE
Add an option to enable eval

### ISSUE THREAD

**Issue by xXKeyleXx** [TheGoddessInari/rambox#73]
It would be nice to have an option to (re)enable `eval` for a (custom) service.

I know sites should not use `eval` but some site I want to use as a service still do it.
As simple checkbox in the service options that is unchecked by default would be great.

Thank you for your great work!

**Comment by TheGoddessInari** [comment]
As pointed out in #79, perhaps the better idea for the present time is to log to console, and hope interested parties (including myself) can get through to affected products.

Many things are now silently capturing the exceptions thrown if you try to use a blocked eval(), so you get an entirely silent failure and the exception thrown never matters. Hopefully they aren't blocking console.log. 🖤

**Comment by xXKeyleXx** [comment]
Well yeah that's an option too 😅 Thanks anyway.
