### ISSUE TITLE
0.5.18: Wrong Menus Position

### ISSUE THREAD

**Issue by LiBOSS-CZ** [TheGoddessInari/rambox#74]
### Steps to reproduce

1.  Fresh Windows 10 Pro 1809 Build
2.  Fresh Rambox Install
3. 

### Expected behavior

Menus in right positions.

### Actual behavior

Menus moved down.
![rambox_error](https://user-images.githubusercontent.com/41294900/50385815-2849ae80-06dc-11e9-8ede-75e044cd5d75.png)

### ENVIRONMENT

> Rambox-OS: v0.5.18

> OS: Windows 10 Pro v1809

> Arch: x64

> BuildVersion: 0172bec

> Does this happen upstream: yes, no, unknown, or N/A

**Comment by TheGoddessInari** [comment]
It's missing window title and icon as well, which probably means some kind of error happened. Any errors on the dev console?

**Comment by LiBOSS-CZ** [comment]
I am sorry, but I can't add any other information. I had to do one more reinstall of the system and now it is OK. I will try it in VM in next few days.

**Comment by TheGoddessInari** [comment]
I'll close this issue then. Feel free to comment if there are any more problems. I'm not locking stuff if it's closed, nor is that a discouragement to comment or participate. It just means the issue can't be considered active. There are still probably some race conditions from upstream.
