### ISSUE TITLE
Messenger doesn't start properly

### ISSUE THREAD

**Issue by LGreenberger** [TheGoddessInari/rambox#76]
### Steps to reproduce

1. Create Messenger app service
2. 
3. 

### Expected behavior

Should prompt for user credentials on first run.

### Actual behavior

Spinning wheel icon is shown and nothing else.
![image](https://user-images.githubusercontent.com/16126495/50730428-723e8580-111b-11e9-94d2-e817d9b2ae39.png)

### ENVIRONMENT

> Rambox-OS: v0.5.18

> OS: Windows 10

> Arch: x64

> BuildVersion:  0172bec (HEAD, origin/master, origin/HEAD, master) Mon, 10 Dec 2018 01:02:46 -0800

> Does this happen upstream: yes, no, unknown, or N/A
unknown

**Comment by LiBOSS-CZ** [comment]
Same for my friend. Clicking on the "not on facebook" at the bottem loads whole facebook page with user logged in, but this is not clean and refine solution.

**Comment by TheGoddessInari** [comment]
I'm trying to figure out what's needed for a fix or clean workaround. Anything I've tried so far hasn't resulted in any progress.

Would anyone be able to tell me if it's currently working in upstream `Rambox CE` or any other (similar), Franz, or another similar product?

**Comment by BuildTheRobots** [comment]
I can confirm that Rambox Community Edition does indeed load the Facebook Messager login screen correctly.

Version tested: https://github.com/ramboxapp/community-edition/releases/download/0.6.3/Rambox-0.6.3-linux-amd64.deb
