### ISSUE TITLE
Google calendar does not load.

### ISSUE THREAD

**Issue by alexbrodersen** [TheGoddessInari/rambox#78]
### Steps to reproduce

1. Add google calendar as a custom service
2. Sign-in

### Expected behavior

Operate gcal as normal.

### Actual behavior

Perpetual loading bar at top of screen + nothing happens when elements are clicked.

### ENVIRONMENT

> Rambox-OS: v0.5.18

> OS: Ubuntu 18.04.1 LTS

> Arch: x64 

> Does this happen upstream: Does not occur in rambox-CE 0.6.3. Also has not occurred with rambox-os in this past.

**Comment by TheGoddessInari** [comment]
Try `master`, since eval was reenabled.

**Comment by alexbrodersen** [comment]
Works great, thanks!
