### ISSUE TITLE
[Feature request] Adding Viber support

### ISSUE THREAD

**Issue by mimecry** [TheGoddessInari/rambox#82]
Hi, thank you very much for this fork. I was wondering if it's possible to add Viber support even without the presence of a web client, as someone has managed to do for Franz: https://github.com/ned-kelly/viber-franz.

How feasible do you think this will be?

**Comment by TheGoddessInari** [comment]
It says it's running docker, so it's probably something you could run and then add as a custom service.
It's obviously not something that could be integrated directly however.

**Comment by mimecry** [comment]
thanks for the answer, i'll look into getting it to run as a custom service.
