### ISSUE TITLE
Fastmail stuck on loading screen

### ISSUE THREAD

**Issue by Stadicus** [TheGoddessInari/rambox#84]
The Fastmail component is stuck on the loading screen, no progress even after a few minutes. Other components work fine.

![screenshot_20190125_082419_rambox-os - fastmail](https://user-images.githubusercontent.com/19550140/51731235-a7832700-207a-11e9-9b91-885832c38386.png)

	
	-
	> Rambox 0.5.18
	> Electron 3.0.10
	> linux x64 4.19.13-1-MANJARO
	> 480daca  (HEAD, origin/master, origin/HEAD, master) Fri, 11 Jan 2019 13:08:38 -0800

**Comment by TheGoddessInari** [comment]
Your version is almost certainly why, try current master. :)

**Comment by Stadicus** [comment]
Unfortunately the issue persists. The new build started up with my old config, I removed all services and added Fastmail again. Do I need to purge the previous config more thoroughly?  

![screenshot_20190125_115208](https://user-images.githubusercontent.com/19550140/51741687-ee334a00-2097-11e9-80ee-3df239228df5.png)

**Comment by TheGoddessInari** [comment]
That's showing the same old build from the 11th as mentioned in the first post. I'm showing that build artifacts are still updating correctly for Linux. What package are you using?
You shouldn't be needing to purge any user config in general. WhatsApp updates requiring that was some weirdness relating to WhatsApp design, and could be handled specifically for affected tabs stuck on login errors.

**Comment by Stadicus** [comment]
Thanks, good catch. I did not uninstall the previous version and with `npm start` somehow the previous version started. 

I compiled it and use now the correct AppImage (as I'm on Manjaro / Arch). Everything works fine, thanks for your help!
