### ISSUE TITLE
It appears that one cannot use both the original Rambox and this fork at the same time

### ISSUE THREAD

**Issue by fortran77** [TheGoddessInari/rambox#88]
Would it be possible to rename this fork slightly differently, e.g., Rambox-OS? Then Rambox and Rambox-OS could be run at the same time.

I noticed that the packaged downloads are called Rambox-OS but internally the program is still Rambox, apparently.

**Comment by TheGoddessInari** [comment]
As mentioned previously in #32, it's a problem with electron effectively invalidating data (not just requiring a rename) if your package name changes.

I'll get to renaming to Hamsket soon, have to make a release before that.

I was trying to track down a heisenbug and getting distracted by other stuff. I still respond to issues, emails, etc. :)

**Comment by fortran77** [comment]
Thanks, sorry I missed that existing issue about renaming.
