### ISSUE TITLE
Rambox doesn't get focus when clicking on a notification

### ISSUE THREAD

**Issue by MatMaul** [TheGoddessInari/rambox#92]
I am using the last nightly, on a Fedora 29 with the RPM package, on Gnome 3 X11.
When I click on a notification I expect Rambox to get into foreground and focus, plus switch to the service where the notif comes from.
At least foreground+focus was working with last official Rambox CE but not anymore here.
For the service switch I have some doubts but I think it was there too.

**Comment by MatMaul** [comment]
And thanks for taking over the CE edition :) Also if you could update Electron, there is a pretty severe CVE in Chrome that has been patched in 4.0.8.

**Comment by TheGoddessInari** [comment]
Thanks for letting me know about the CVE, builds are updated now. 

I'll look into what's going on with notifications as soon as I can. The electron updates fix a lot of problems, but can cause some others. I suspect that's what's happening here.

**Comment by MatMaul** [comment]
Great ! I don't know if this is the update but clicking the notification now switches to the good service. However Rambox is still not taken into foreground on my Fedora 29 + Gnome, works fine with Mac.

**Comment by MatMaul** [comment]
One guess regarding that: could it be some wrong window name targeted by the notification that changed when the project got renamed to RamboxOS ?

**Comment by TheGoddessInari** [comment]
See if  26b0b1f helps with this problem. It really honestly should.

**Comment by MatMaul** [comment]
It does not :(
Also tried the last one with electron 4.1.1 update but still no luck.
Thanks for trying. I had a quick look at the code and the electron bugs but no clue.

**Comment by TheGoddessInari** [comment]
Hmm. Unless there's a problem with the library packaging I don't know about, could it be related to GNOME 3? I always had notification problems when using GNOME in general.

Unless I'm missing something obvious, the notification data is getting transferred correctly through the process now. I've no idea why a generic icon shows up on occasion, but I think that's up to the webapp to get right.

Originally the notification function was doing some open coding, as well as not doing the focus event correctly, but now it is.

Unfortunately, a lot of problems come down to how Electron is or isn't doing things correctly, and with filed electron issues getting totally ignored, I don't know what to do about them other than slowly try to work on a replacement architecture and groundwork that doesn't involve Electron in any way.

**Comment by MatMaul** [comment]
...... So I don't know why but the electron doc is wrong, or there is a bug. I think there is a bug :)
If I add a `focus()` right after the `show()` here:
https://github.com/TheGoddessInari/rambox/blob/master/app/ux/WebView.js#L554
It works... The doc clearly states it should do the focus but hey...

**Comment by TheGoddessInari** [comment]
That's...very weird, but doesn't seem like it'd hurt anything.

**Comment by TheGoddessInari** [comment]
Really good catch, by the way, @MatMaul.

**Comment by TheGoddessInari** [comment]
On a tangentially related note, not sure why Notifications work great sometimes (showing full service icons and info), and other times only the most basic information. I'm assuming for the time being that it's the service's fault (ie, ICQ), but please correct me if I'm wrong.

**Comment by LiBOSS-CZ** [comment]
Hello, 
I have related issue. I am using Windows 10. If I click on Whatsapp/Skype notification then Rambox gets maximized, but for Hangouts clicking on notification just hide the notification "square and Rambox stays in task bar.

**Comment by TheGoddessInari** [comment]
And this is with 7937d8d? I'll look into it.

**Comment by LiBOSS-CZ** [comment]
No. It was with the previous version. I will try this new one.

**Comment by TheGoddessInari** [comment]
Just checked with Hangouts. I'm not sure what's going on there. Sometimes it works, sometimes it doesn't.

Hangouts itself is ridiculously inconsistent and acts strange even with passivetimeouts and timergranularity turned off.

Pretty sure it's not related to this issue.

**Comment by LiBOSS-CZ** [comment]
OK. Anyway thanks for check
