### ISSUE TITLE
Add shortcuts for moving between applications

### ISSUE THREAD

**Issue by snowe2010** [TheGoddessInari/rambox#94]
Hi, I hate touching my mouse, but I love the idea of Rambox-OS. Is there any way to add shortcuts in to navigate between the apps in rambox themselves? Or a way to expose shortcuts to jump to individual apps to the underlying OS? I use hammerspoon to navigate and being able to jump straight to apps is a huge gain.

**Comment by TheGoddessInari** [comment]
It would be considerable redesign just for OSX to expose each browser window separately.

There are the standard shortcuts for switching tabs, and I'll likely reinstate the ctrl/cmd 1-9 shortcuts for the first 9 tabs, assuming Electron doesn't somehow stop me from it.

**Comment by snowe2010** [comment]
What are the standard shortcuts for switching tabs? I don't see anything in the menubar indicating the shortcuts I can use.

**Comment by TheGoddessInari** [comment]
Oops. It should be Ctrl-Tab (forward) / Control-Shift-Tab (backwards), same as any other tab switching on OSX, but I realized it'd probably use cmd-tab on OSX which would conflict. I'll fix that.

Is Command or Control + PageUp/PageDown the idiomatic/most common alternate on OSX?

I'm reading that `Command + Shift + ]` is another very normal thing on OSX?

**Comment by snowe2010** [comment]
I have my machine so customized I don't actually know what is normal. Just having any shortcut at all is fine because users can just override the shortcut in their keyboard settings. And yes Cmd + anything is likely to conflict. I think I've seen `Command + Shift + ]` before, so that's probably fine. I actually hate it when applications use PageUp/PageDown because many laptop keyboards don't have those shortcuts, so it's then impossible to use that on a laptop (or on a custom keyboard like the Planck or Iris which might not use those keys)

**Comment by TheGoddessInari** [comment]
Right, no worries. I was specifically asking so I could make sure to get it right, and add the right Mac-specific shortcuts as well.

It was never end-user configurable with upstream. I could expose the menus for all of this, so Mac users could cheerily reconfigure these shortcuts at-will, but it is truly horribly ugly as they don't really fit in anywhere and it was the most reasonable workaround for the new behavior.

**Comment by TheGoddessInari** [comment]
I've committed 4f95cfc to fix ctrl-tab type shortcuts as well as added the forementioned bracketing ones. I'll push builds to nightly as soon as it's finished building.

**Comment by snowe2010** [comment]
>It was never end-user configurable with upstream. I could expose the menus for all of this, so Mac users could cheerily reconfigure these shortcuts at-will, but it is truly horribly ugly as they don't really fit in anywhere and it was the most reasonable workaround for the new behavior.

Haha. 

>I've committed 4f95cfc to fix ctrl-tab type shortcuts as well as added the forementioned bracketing ones. I'll push builds to nightly as soon as it's finished building.

Yay! Thank you!
