### ISSUE TITLE
Unable to log in with Master Password set

### ISSUE THREAD

**Issue by ColtonBeery** [TheGoddessInari/rambox#98]
For some reason, I can't use the Master Password feature at all on the latest nightly. It worked fine before updating, and now I can't log in at all. 
I also tried deleting all my files from %appdata%/Rambox to get a completely blank slate, and then setting the Master Password in there, with the same problem. 

### Steps to reproduce

1. Install latest nightly
2. Enable Master Password
3. Restart Rambox
4. Try logging in using Master Password

### Expected behavior

After typing in the Master Password, the program should go to the main screen, allowing me to open my chats. 

### Actual behavior

The program does.... nothing. It just hangs there, as if still waiting for me to type the password in, despite me having tried typing the password in several times. 

### ENVIRONMENT

> Rambox-OS: May 4th Nightly

> OS: Windows 10

> Arch: x64

> BuildVersion: Commit d42dc5c

> Does this happen upstream: No

**Comment by TheGoddessInari** [comment]
This is fixed in 8d6e149.
